create schema portfolio;
grant usage on schema portfolio to anon;

create table portfolio.tbuser (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint tbuser_pkey primary key (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbuser as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbuser to anon;

create table portfolio.tbcredentials (
  id bigint generated by default as identity not null,
  iduser bigint not null,
  email text not null default ''::text,
  password text not null,
  created_at timestamp with time zone not null default now(),
  constraint tbcredentials_pkey primary key (id),
  constraint tbcredentials_iduser_fkey foreign KEY (iduser) references portfolio.tbuser (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbcredentials as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbcredentials to anon;

create table portfolio.tbparties (
  id bigint generated by default as identity not null,
  name text not null,
  entity_type text not null,
  status text not null,
  email text null,
  phone text null,
  document text null,
  created_at timestamp with time zone not null default now(),
  lead_origin text null,
  observations text not null default ''::text,
  constraint tbparties_pkey primary key (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbparties as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbparties to anon;

create table portfolio.tbproject (
  id bigint generated by default as identity not null,
  title text not null,
  status text not null,
  description text null default ''::text,
  created_at timestamp with time zone not null default now(),
  idparties bigint not null,
  total_cost numeric not null,
  total_amount numeric not null,
  total_markup numeric not null,
  origin text not null default ''::text,
  relevance text not null,
  constraint tbprojetos_pkey primary key (id),
  constraint tbproject_idparties_fkey foreign KEY (idparties) references portfolio.tbparties (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbproject as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbproject to anon;

create table portfolio.tbmissions (
  id bigint generated by default as identity not null,
  idproject bigint not null,
  name text not null,
  description text not null,
  status text not null,
  date_start date not null,
  date_end date not null,
  total_amount numeric not null,
  created_at timestamp with time zone not null default now(),
  total_cost numeric not null,
  total_markup numeric not null,
  estimated_amount numeric not null,
  estimated_cost numeric not null,
  estimated_markup numeric not null,
  constraint tbmissions_pkey primary key (id),
  constraint tbmissions_idproject_fkey foreign KEY (idproject) references portfolio.tbproject (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbmissions as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbmissions to anon;

create table portfolio.tbservice (
  id bigint generated by default as identity not null,
  title text not null,
  markup numeric not null,
  price numeric not null,
  cost numeric not null,
  created_at timestamp with time zone not null default now(),
  constraint tbservices_pkey primary key (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbservice as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbservice to anon;

create table portfolio.tbtask (
  id bigint generated by default as identity not null,
  idmission bigint not null,
  idservice bigint not null,
  name text not null,
  description text not null,
  status text not null,
  estimated_hours numeric not null,
  total_hours numeric not null,
  date_start date not null,
  date_end date not null,
  created_at timestamp with time zone not null default now(),
  constraint tbtask_pkey primary key (id),
  constraint tbtask_idmission_fkey foreign KEY (idmission) references portfolio.tbmissions (id),
  constraint tbtask_idservice_fkey foreign KEY (idservice) references portfolio.tbservice (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbtask as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbtask to anon;

create table portfolio.tbattachments (
  id bigint generated by default as identity not null,
  type text not null,
  origin text not null,
  idorigin bigint not null,
  source text not null,
  created_at timestamp with time zone not null default now(),
  idref bigint not null default '0'::bigint,
  description text not null,
  constraint tbanexo_pkey primary key (id)
) TABLESPACE pg_default;

create policy "allow all" on portfolio.tbattachments as PERMISSIVE for all to anon using (true);
grant select, insert, update, delete on portfolio.tbattachments to anon;