create database portfolio;
using portfolio;

create table tbuser (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint tbuser_pkey primary key (id)
) TABLESPACE pg_default;

create table tbcredentials (
  id bigint generated by default as identity not null,
  iduser bigint not null,
  email text not null default ''::text,
  password text not null,
  created_at timestamp with time zone not null default now(),
  constraint tbcredentials_pkey primary key (id),
  constraint tbcredentials_iduser_fkey foreign KEY (iduser) references tbuser (id)
) TABLESPACE pg_default;